files:
  - 
    source: '/po/*.pot'
    translation: '/po/%locale_with_underscore%.po'
  - 
    source: /src/_locales/ru/messages.json
    translation: '/src/_locales/%two_letters_code%/messages.json'
