// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/gulp-debug/gulp-debug.d.ts
declare module 'gulp-debug' {
    interface IOptions {
        title?: string;
        minimal?: boolean;
    }

    function debug(options?: IOptions): NodeJS.ReadWriteStream;

    namespace debug {}

    export = debug;
}
