/// <reference path="./libs/chrome/chrome.d.ts"/>
/// <reference path='./libs/angularjs/angular.d.ts' />
/// <reference path="./libs/angular-ui-router/angular-ui-router.d.ts"/>
/// <reference path="./libs/vk/openapi.d.ts"/>
/// <reference path="./libs/helpers/helpers.d.ts"/>
/// <reference path="./libs/linkifyjs/linkifyjs.d.ts"/>
/// <reference path="./StorageApp/storage.d.ts"/>
/// <reference path="./StorageApp/StorageService.ts"/>
/// <reference path="./VkApp/js/VkService.ts"/>
